version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./.cache/grafana:/var/lib/grafana
    networks:
      - my-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./settings/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge
