version: '3.8'

services:
  api:
    build:
      context: ./shop_api  # Указываем, что Dockerfile и проект находятся в ./shop_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./shop_api:/app  # Монтируем папку ./shop_api вместо всей директории
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./shop_api/settings/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
