global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: demo-service-local
    metrics_path: /metrics
    static_configs:
      - targets:
          - local:8080
remote_write:
  - url: "http://localhost:9090/api/v1/write"
